name: my_flutter_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


#   audio_recorder: any #录音、播放
#   flutter_sound: ^1.1.5#录音
#   dropdown_menu: ^1.1.0#下拉菜单
#   simple_permissions:#权限获取
#   easy_alert:#弹框
#   amap_location: any #高德地图
#   location: any #gogle位置获取
#   barcode_scan 0.0.8#二维码识别qr_mobile_vision: ^0.1.0 #二维码识别 这个不好用
#   flutter_screenutil: ^0.3.0#屏幕适配工具类  
#   flutter_spinkit: ^2.1.0#加载等待框
#   lpinyin: ^1.0.6#汉字转拼音
#   shimmer: ^0.0.4#微光效果控件
#   qr_flutter: ^1.1.3#二维码生成
#   url_launcher: any#启动URL的Flutter插件。支持网络，电话，短信和电子邮件
#   datetime_picker_formfield: ^0.1.3#时间选择控件
#   flutter_picker: '^1.0.0'#选择器
#   common_utils: '^1.0.1'#工具类 时间、日期、日志等
#   flutter_html: '^0.8.2'#静态html标记呈现为Flutter小部件
#   fluwx: '^0.3.0'#微信支付、分享、登录
#   tobias: '^ 0.0.6'#支付宝
#   cupertino_icons: '^0.1.2'#小图标控件
#   http: '^0.11.3+16'#网络请求
#   html: '^0.13.3'#html解析
#   image_picker: '^0.4.5'#图片选择（相册或拍照）
#   flutter_webview_plugin: any#webview展示
#   fluttertoast: any#toast提示框
#   shared_preferences: '^0.4.2'#shared_preferences存储
#   transparent_image: '^0.1.0'#透明图片控件
#   flutter_swiper : '^1.0.2'#轮播图
#   charts_flutter: '^0.4.0'#统计图表
#   path_provider: '^0.4.1'#获取系统文件
#   cached_network_image: '0.4.1'#加载网络图片并本地缓存
#   sqflite: '^0.11.0+1'#sqllite数据库操作
#   pull_to_refresh: '^1.1.5'#下拉刷新上拉加载更多
#   video_player: '0.6.1'#视频播放
#   collection: '1.14.11'#集合操作工具类
#   device_info: '0.2.1'#获取手机信息
#   flutter_svg: '^0.3.2'#展示svg图标控件
#   intl: any#国际化工具类
#   connectivity: '0.3.1'#链接网络
#   flutter_staggered_grid_view:#瀑布流展示控件
#   flutter_file_manager:#文件管理
#   loader_search_bar:#导航栏搜索控件
#   flutter_image_compress : any#图片压缩
#   ota_update : any#App下载更新
#   flutter_slidable：#item侧滑控件
dependencies:
  json_annotation: ^2.4.0
  path_provider: ^1.1.2
  sqflite: ^1.1.6
  event_bus: ^1.1.0
  fluro: 1.4.0
  fluttertoast: 2.2.3
  photo: 0.2.0
  pull_to_refresh: ^1.4.9
  fluwx: ^1.0.3
  tobias: ^1.0.0
  barcode_scan: 0.0.8	
  qr_flutter: 1.1.6
  dio: ^2.1.13
  provide: ^1.0.2
  url_launcher: ^5.0.1
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  json_serializable: ^3.0.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/home_ico.png
    - images/home.png
    - images/message_ico.png
    - images/message.png
    - images/bbs_ico.png
    - images/bbs.png
    - images/person_ico.png
    - images/person.png
    - images/bg.png
    - images/huangguan.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
